[package]
name = "cfd_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
ndarray = "0.15"
plotters = "0.3"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
